server:
  port: 8200
dubbo:
  application:
    name: retailer-center-server
  registry:
      protocol: zookeeper
      address: 127.0.0.1
      port: 2181
      timeout: 3000
  protocol:
      port: 20880
      name: dubbo
